spring:
  datasource:
    url: jdbc:h2:file:./data/db/cubeia-wallet;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    change-log: classpath:/db/changelog/changelog-1.yaml